import type { Metadata, Viewport } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import { JsonLd } from "@/components/seo/json-ld";
import { RegisterSW } from "@/components/pwa/register-sw";
import { InstallPrompt } from "@/components/pwa/install-prompt";
import { Providers } from "@/components/providers";
import { WebVitals } from "@/components/analytics/web-vitals";

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  display: "swap",
  preload: true,
});

const siteConfig = {
  name: "CueSports Africa",
  description:
    "Africa's premier cue sport tournament and player management platform. Host pool, snooker, and billiards events, track Elo ratings, and collect fees via M-Pesa.",
  url: "https://cuesports.africa",
  ogImage: "https://cuesports.africa/og-image.png",
  twitterHandle: "@cuesportsafrica",
  email: "info@cuesports.africa",
  phone: "+254700000000",
  address: {
    city: "Nairobi",
    country: "Kenya",
  },
};

export const metadata: Metadata = {
  metadataBase: new URL(siteConfig.url),
  title: {
    default: `${siteConfig.name} | Professional Pool Tournament Management`,
    template: `%s | ${siteConfig.name}`,
  },
  description: siteConfig.description,
  keywords: [
    // Short-tail (high volume)
    "pool",
    "snooker",
    "billiards",
    "8-ball",
    "9-ball",
    "pool Africa",
    "snooker Africa",
    "pool Kenya",
    "snooker Kenya",
    "pool tournament",
    "snooker tournament",
    "pool rankings",
    "pool league",
    "cue sports",
    "pool table",
    "pool player",
    "pool club",
    // Mid-tail (moderate competition)
    "pool tournaments Africa",
    "snooker tournaments Africa",
    "billiards Africa",
    "pool tournaments Kenya",
    "snooker tournaments Kenya",
    "pool tournaments Nairobi",
    "pool rankings Kenya",
    "pool rankings Africa",
    "snooker rankings Africa",
    "pool league Africa",
    "pool league Kenya",
    "8-ball tournament Africa",
    "9-ball tournament Africa",
    "pool competition Africa",
    "snooker competition Kenya",
    "pool club near me",
    "pool hall Kenya",
    "Elo rating pool",
    "pool player rankings",
    "tournament bracket generator",
    "pool tournament app",
    // Long-tail (low competition, high intent)
    "how to join pool tournament Africa",
    "pool tournament registration online",
    "pool tournament management software",
    "snooker tournament management app",
    "M-Pesa pool tournament payments",
    "online pool tournament registration Kenya",
    "pool tournament bracket generator free",
    "Elo rating system billiards",
    "professional pool platform Africa",
    "pool tournament organizer software",
    "live pool match scoring app",
    "pool player rating system Africa",
    "snooker league management software",
    "pool tournament results Africa",
    "pool tournament schedule Kenya",
    "best pool players Africa",
    "top snooker players Kenya",
    "pool tournament prize money Africa",
    "how to organize pool tournament",
    "pool tournament rules 8-ball",
    "cuesports Africa platform",
    "cue sport",
    "cue sport Africa",
    "cue sport Kenya",
    "cue sport tournament",
    "cue sport rankings",
    "cue sport league",
    // Brand & keyword variations
    "cuesport africa",
    "cuesports africa",
    "pool tournament africa",
    "8 ball pool africa",
    "African pool tournament",
    "African billiards",
    "pool player rankings africa",
  ],
  authors: [{ name: siteConfig.name, url: siteConfig.url }],
  creator: siteConfig.name,
  publisher: siteConfig.name,
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: siteConfig.url,
    siteName: siteConfig.name,
    title: `${siteConfig.name} | Professional Pool Tournament Management`,
    description: siteConfig.description,
    // Images are auto-generated by app/opengraph-image.tsx (1200x630)
    // with fallback to /og-image.png for crawlers that don't follow the dynamic route
    images: [
      {
        url: "/opengraph-image",
        width: 1200,
        height: 630,
        alt: `${siteConfig.name} - Africa's Premier Cue Sport Platform`,
        type: "image/png",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: `${siteConfig.name} | Professional Pool Tournament Management`,
    description: siteConfig.description,
    site: siteConfig.twitterHandle,
    creator: siteConfig.twitterHandle,
    // Image auto-generated by app/twitter-image.tsx (1200x630)
    images: [
      {
        url: "/twitter-image",
        width: 1200,
        height: 630,
        alt: `${siteConfig.name} - Africa's Premier Cue Sport Platform`,
      },
    ],
  },
  verification: {
    google: "wE3gZSX-16lXepHvBUhrMuLOBvIIw7-HX0dy9Gh06VA",
    yandex: "265f97cd0ed2af0a",
    other: {},
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  alternates: {
    canonical: siteConfig.url,
  },
  category: "Sports",
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#05161a" },
    { media: "(prefers-color-scheme: dark)", color: "#05161a" },
  ],
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  userScalable: true,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* PWA Configuration */}
        <link rel="manifest" href="/manifest.json" />
        <link rel="apple-touch-icon" href="/icons/icon-192x192.png" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="apple-mobile-web-app-title" content="CueSports" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="application-name" content="CueSports Africa" />
        {/* Bing & multi-engine directives */}
        <meta name="bingbot" content="index, follow, max-snippet:-1, max-image-preview:large" />
        {/* Geo meta tags for Bing/DuckDuckGo local SEO */}
        <meta name="geo.region" content="KE" />
        <meta name="geo.placename" content="Nairobi" />
        <meta name="geo.position" content="-1.2921;36.8219" />
        <meta name="ICBM" content="-1.2921, 36.8219" />
        <JsonLd
          data={{
            "@context": "https://schema.org",
            "@type": ["Organization", "SportsOrganization"],
            name: siteConfig.name,
            url: siteConfig.url,
            logo: `${siteConfig.url}/logo.png`,
            description: siteConfig.description,
            email: siteConfig.email,
            telephone: siteConfig.phone,
            sport: "Billiards",
            areaServed: {
              "@type": "Continent",
              name: "Africa",
            },
            address: {
              "@type": "PostalAddress",
              addressLocality: siteConfig.address.city,
              addressCountry: siteConfig.address.country,
            },
            sameAs: [
              "https://facebook.com/cuesportsafrica",
              "https://twitter.com/cuesportsafrica",
              "https://instagram.com/cuesportsafrica",
              "https://youtube.com/cuesportsafrica",
            ],
          }}
        />
        <JsonLd
          data={{
            "@context": "https://schema.org",
            "@type": "WebSite",
            name: siteConfig.name,
            url: siteConfig.url,
            potentialAction: {
              "@type": "SearchAction",
              target: {
                "@type": "EntryPoint",
                urlTemplate: `${siteConfig.url}/search?q={search_term_string}`,
              },
              "query-input": "required name=search_term_string",
            },
          }}
        />
      </head>
      <body
        className={`${sora.variable} font-sans antialiased min-h-screen flex flex-col`}
        suppressHydrationWarning
      >
        <Providers>
          <WebVitals />
          {children}
        </Providers>
        <RegisterSW />
        <InstallPrompt />
      </body>
    </html>
  );
}
